name: First_Workflow

on:
  push:
    branches:
      -main
jobs:
  example-job:
    runs-on: ununtu-latest

    steps:
      - name: Print a welcome message
        run: echo "Welcome to the first github actions workflow"

      - name: Checkout 
        uses: actions/checkout@v6.0.0

      - name: list repository files
        run: ls -la
